name: zenon_syrius_wallet_flutter
description: Zenon cross-platform non-custodial wallet
publish_to: none

environment:
  sdk: '>=3.0.1'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.69.0
  overlay_support: ^2.1.0
  lottie: ^3.1.2
  dotted_border: ^2.0.0+2
  flutter_svg: ^2.0.0+1
  flutter_vector_icons: ^2.0.0
  expandable: ^5.0.1
  marquee_widget: ^1.2.0
  layout: ^1.0.2
  flutter_staggered_grid_view: ^0.7.0
  flip_card: ^0.7.0
  flutter_flip_card: ^0.0.5
  auto_size_text: ^3.0.0
  window_manager: ^0.4.2
  stacked: ^3.4.1
  path_provider: ^2.1.0
  rxdart: ^0.28.0
  hive: ^2.0.5
  url_launcher: ^6.1.12
  provider: ^6.0.2
  intl: any
  package_info_plus: ^8.0.2
  device_info_plus: ^10.1.2
  infinite_scroll_pagination: ^4.0.0
  share_plus: ^10.0.2
  page_transition: ^2.0.4
  file_selector: ^1.0.0
  pretty_qr_code: ^3.2.1
  desktop_drop: ^0.5.0
  validators: ^3.0.0
  wakelock_plus: ^1.1.1
  number_selector: ^1.0.5
  znn_sdk_dart:
    git:
      url: https://github.com/maznnwell/znn_sdk_dart.git
      ref: refactor
  znn_ledger_dart:
    git:
      url: https://github.com/zenon-network/znn_ledger_dart.git
      ref: v0.0.5
  json_rpc_2: ^3.0.2
  path: ^1.8.2
  ffi: ^2.1.0
  get_it: ^7.2.0
  hex: ^0.2.0
  local_notifier: ^0.1.5
  tray_manager: ^0.2.0
  open_filex: ^4.3.2
  launch_at_startup: ^0.3.1
  logging: ^1.2.0
  collection: ^1.17.0
  app_links: ^6.3.2
  walletconnect_flutter_v2: ^2.0.14
  preference_list: ^0.0.1
  screen_capturer: ^0.2.3
  zxing2: ^0.2.0
  image: ^4.0.10
  clipboard_watcher: ^0.2.0
  wallet_connect_uri_validator: ^0.1.0
  big_decimal: ^0.5.0
  ai_barcode_scanner: ^5.2.1
  version: ^3.0.0
  mutex: ^3.1.0
  retry: ^3.1.2
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5


dependency_overrides:
  znn_sdk_dart:
    git:
      url: https://github.com/maznnwell/znn_sdk_dart.git
      ref: refactor

dev_dependencies:
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  flutter_lints: ^5.0.0
  dependency_validator: ^4.1.1
  mocktail: ^1.0.4
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/i18n/
    - assets/lottie/
    - assets/svg/